// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzemg4G8S9h_JwR7x45ZXsCS_0Sa1CTU',
    appId: '1:462598414836:web:94fe8dad9d6f2d155b99a1',
    messagingSenderId: '462598414836',
    projectId: 'dhiraj-ayu-academy',
    authDomain: 'dhiraj-ayu-academy.firebaseapp.com',
    storageBucket: 'dhiraj-ayu-academy.firebasestorage.app',
    measurementId: 'G-9KL7JGLERZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZjW2GaKHamUhF7_BR-Ok0JkWu0Dkviw',
    appId: '1:462598414836:android:d977b7761965642e5b99a1',
    messagingSenderId: '462598414836',
    projectId: 'dhiraj-ayu-academy',
    storageBucket: 'dhiraj-ayu-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeaxIlEcK8s-J9QtPos6JVv90wZDDS0w',
    appId: '1:462598414836:ios:283f7619b851bad75b99a1',
    messagingSenderId: '462598414836',
    projectId: 'dhiraj-ayu-academy',
    storageBucket: 'dhiraj-ayu-academy.firebasestorage.app',
    iosBundleId: 'com.example.dhirajAyuAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJeaxIlEcK8s-J9QtPos6JVv90wZDDS0w',
    appId: '1:462598414836:ios:283f7619b851bad75b99a1',
    messagingSenderId: '462598414836',
    projectId: 'dhiraj-ayu-academy',
    storageBucket: 'dhiraj-ayu-academy.firebasestorage.app',
    iosBundleId: 'com.example.dhirajAyuAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYzemg4G8S9h_JwR7x45ZXsCS_0Sa1CTU',
    appId: '1:462598414836:web:1230c67df31c91e95b99a1',
    messagingSenderId: '462598414836',
    projectId: 'dhiraj-ayu-academy',
    authDomain: 'dhiraj-ayu-academy.firebaseapp.com',
    storageBucket: 'dhiraj-ayu-academy.firebasestorage.app',
    measurementId: 'G-E3CQXK8DCN',
  );
}
